# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('biztype', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
    ]
