# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_biz_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
