# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_auto_20160827_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
