# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('confession', models.CharField(max_length=300)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
